Fixed flatpak builder for Github Action

diff --git a/.github/workflows/flatpak.yml b/.github/workflows/flatpak.yml
--- a/.github/workflows/flatpak.yml
+++ b/.github/workflows/flatpak.yml
@@ -43,7 +43,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '22'
+          node-version: "22"
 
       - name: Setup bun
         uses: oven-sh/setup-bun@v2
@@ -82,17 +82,17 @@ jobs:
           flatpak install --user --noninteractive flathub org.freedesktop.Sdk.Extension.node22//24.08
           flatpak install --user --noninteractive flathub org.freedesktop.Sdk.Extension.rust-stable//24.08
 
-      # - name: Build Tauri application
-      #   run: |
-      #     bun run tauri:build:fast
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
-      #     TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
+      - name: Build Tauri application
+        run: |
+          bun run tauri:build:fast
 
       - name: Build Flatpak using manifest
         run: |
-          flatpak-builder --force-clean --repo=repo --install-deps-from=flathub build-dir flatpak/com.tcs.taskflow.local.yml
+          flatpak-builder --disable-cache --force-clean --user --install-deps-from=flathub --repo=repo build flatpak/com.tcs.taskflow.yml
+          if [ $? -ne 0 ]; then
+            echo "Flatpak build failed"
+            exit 1
+          fi
 
       - name: Create Flatpak bundle
         run: |
